import packageJson from "../../package.json";

describe("Package JSON", () => {
  test("contains the correct package name", () => {
    expect(packageJson.name).toBe("gtcrm");
  });

  test("contains the correct dependencies", () => {
    expect(packageJson.dependencies).toEqual({
      "@emotion/react": "^11.11.1",
      "@emotion/styled": "^11.11.0",
      "@hello-pangea/dnd": "^16.5.0",
      "@mui/icons-material": "^5.15.19",
      "@mui/lab": "^5.0.0-alpha.66",
      "@mui/material": "^5.15.19",
      "@mui/system": "^5.14.18",
      "@mui/x-date-pickers": "^6.20.1",
      "@reduxjs/toolkit": "^1.9.5",
      "@testing-library/user-event": "^14.5.1",
      "@tiptap/extension-character-count": "^2.4.0",
      "@tiptap/extension-mention": "^2.4.0",
      "@tiptap/pm": "^2.4.0",
      "@tiptap/react": "^2.4.0",
      "@tiptap/starter-kit": "^2.4.0",
      "@tiptap/suggestion": "^2.4.0",
      "@vitest/ui": "^1.5.2",
      axios: "^1.6.8",
      "chart.js": "^4.4.0",
      classnames: "^2.5.1",
      "crypto-js": "^4.2.0",
      "d3-hierarchy": "^3.1.2",
      "d3-scale": "^4.0.2",
      "d3-timer": "^3.0.1",
      "date-fns": "^2.29.3",
      dayjs: "^1.11.9",
      "font-awesome": "^4.7.0",
      "js-cookie": "^3.0.5",
      "jwt-decode": "^3.1.2",
      "lottie-web": "^5.12.2",
      "pdfjs-dist": "^4.4.168",
      "re-resizable": "^6.9.11",
      react: "^18.2.0",
      "react-apexcharts": "^1.4.0",
      "react-beautiful-dnd": "^13.1.1",
      "react-chartjs-2": "^5.2.0",
      "react-d3-tree": "^3.6.1",
      "react-dom": "^18.2.0",
      "react-draggable": "^4.4.6",
      "react-email-editor": "^1.7.9",
      "react-error-boundary": "^4.0.11",
      "react-funnel-pipeline": "^0.2.0",
      "react-infinite-scroll-component": "^6.1.0",
      "react-intersection-observer-hook": "^2.1.1",
      "react-joyride": "^2.6.2",
      "react-masonry-css": "^1.0.16",
      "react-medium-image-zoom": "^5.1.9",
      "react-multi-date-picker": "^3.3.4",
      "react-pdf": "^9.1.0",
      "react-quill": "2.0.0",
      "react-redux": "^8.1.3",
      "react-router-dom": "^6.22.1",
      "react-simple-maps": "^3.0.0",
      "react-slick": "^0.29.0",
      "react-toastify": "^9.1.2",
      "react-tooltip": "^4.5.1",
      reactflow: "^11.10.1",
      recharts: "^2.10.4",
      rsuite: "^5.49.0",
      sass: "^1.77.4",
      "simplebar-react": "^3.2.3",
      "styled-components": "^6.1.11",
      "tippy.js": "^6.3.7",
      "web-vitals": "^3.5.2",
      yup: "^1.3.2",
    });
  });

  // Add additional tests as needed
});
