// data for default map
export const defaultMapArray = [
    {
        state_name: "Delhi",
        state_code: "DL",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Uttar Pradesh",
        state_code: "UP",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Haryana",
        state_code: "HR",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Maharashtra",
        state_code: "MH",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "West Bengal",
        state_code: "WB",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Karnataka",
        state_code: "KA",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Rajasthan",
        state_code: "RJ",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Telangana",
        state_code: "TS",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Madhya Pradesh",
        state_code: "MP",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Gujarat",
        state_code: "GJ",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Meghalaya",
        state_code: "ML",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Mizoram",
        state_code: "MZ",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Dadra and Nagar Haveli and Daman and Diu",
        state_code: "DH",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Jharkhand",
        state_code: "JH",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Uttarakhand",
        state_code: "UT",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Odisha",
        state_code: "OD",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Bihar",
        state_code: "BR",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Tamil Nadu",
        state_code: "TN",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Tripura",
        state_code: "TR",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Kerala",
        state_code: "KL",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Lakshadweep",
        state_code: "LD",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Himachal Pradesh",
        state_code: "HP",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Sikkim",
        state_code: "SK",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Jammu and Kashmir",
        state_code: "JK",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Punjab",
        state_code: "PB",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Arunachal Pradesh",
        state_code: "AR",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Chandigarh",
        state_code: "CH",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Ladakh",
        state_code: "LA",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Andhra Pradesh",
        state_code: "AP",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Assam",
        state_code: "AS",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Manipur",
        state_code: "MN",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Andaman and Nicobar Islands",
        state_code: "AN",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Goa",
        state_code: "GA",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Nagaland",
        state_code: "NL",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Chhattisgarh",
        state_code: "CT",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
    {
        state_name: "Puducherry",
        state_code: "PY",
        total_lead: 0,
        lead_percentage: 0,
        application_percentage: 0,
        application_count: 0,
    },
];